/**
 * Complete ABI for FOUR Trading Platform Contract
 * Contract: 0x5c952063c7fc8610FFDB798152D69F0B9550762b
 */

export const FOUR_TRADING_ABI = [
  // Functions
  "function addLiquidity(address tokenAddress)",
  "function addTemplate(address quote, uint256 initialLiquidity, uint256 maxRaising, uint256 totalSupply, uint256 maxOffers, uint256 minTradingFee)",
  "function buyToken(address token, address to, uint256 amount, uint256 maxFunds) payable",
  "function buyToken(address token, uint256 amount, uint256 maxFunds) payable",
  "function buyTokenAMAP(address token, address to, uint256 funds, uint256 minAmount) payable",
  "function buyTokenAMAP(address token, uint256 funds, uint256 minAmount) payable",
  "function createToken(bytes args, bytes signature) payable",
  "function createToken(bytes args) payable",
  "function grantDeployer(address account)",
  "function grantOperator(address account)",
  "function grantRole(bytes32 role, address account)",
  "function initialize()",
  "function initialize(address signer, address feeRecipient, address tokenCreator, address referralRewardKeeper, uint256 launchFee)",
  "function renounceOwnership()",
  "function renounceRole(bytes32 role, address account)",
  "function revokeDeployer(address account)",
  "function revokeOperator(address account)",
  "function revokeRole(bytes32 role, address account)",
  "function sellToken(uint256 origin, address token, uint256 amount, uint256 minFunds, uint256 feeRate, address feeRecipient)",
  "function sellToken(uint256 origin, address token, uint256 amount, uint256 minFunds)",
  "function sellToken(uint256 origin, address token, uint256 amount)",
  "function sellToken(address token, uint256 amount, uint256 minFunds)",
  "function sellToken(uint256 origin, address token, address from, uint256 amount, uint256 minFunds, uint256 feeRate, address feeRecipient)",
  "function sellToken(address token, uint256 amount)",
  "function setFeeRecipient(address v)",
  "function setLaunchFee(uint256 v)",
  "function setMinTradingFee(uint256 template, uint256 v)",
  "function setReferralRewardRate(uint256 v)",
  "function setRoleAdmin(bytes32 role, bytes32 adminRole)",
  "function setSigner(address newSigner)",
  "function setTradingFeeRate(uint256 v)",
  "function suspendTrading(address token, bool value)",
  "function transferOwnership(address newOwner)",
  "function upgradeTo(address newImplementation)",
  "function upgradeToAndCall(address newImplementation, bytes data) payable",
  "function withdrawERC20(address token, address to, uint256 amount)",
  "function withdrawEth(address to, uint256 amount)",

  // View/Pure Functions
  "function _feeRecipient() view returns (address)",
  "function _launchFee() view returns (uint256)",
  "function _referralRewardKeeper() view returns (address)",
  "function _referralRewardRate() view returns (uint256)",
  "function _templateCount() view returns (uint256)",
  "function _templates(uint256) view returns (address quote, uint256 initialLiquidity, uint256 maxRaising, uint256 totalSupply, uint256 maxOffers, uint256 minTradingFee)",
  "function _tokenCount() view returns (uint256)",
  "function _tokenCreator() view returns (address)",
  "function _tokenInfoExs(address) view returns (address creator, address founder, uint256 reserves)",
  "function _tokenInfos(address) view returns (address base, address quote, uint256 template, uint256 totalSupply, uint256 maxOffers, uint256 maxRaising, uint256 launchTime, uint256 offers, uint256 funds, uint256 lastPrice, uint256 K, uint256 T, uint256 status)",
  "function _tokens(uint256) view returns (address)",
  "function _tradingFeeRate() view returns (uint256)",
  "function _tradingHalt() view returns (bool)",
  "function calcBuyAmount(tuple(address base, address quote, uint256 template, uint256 totalSupply, uint256 maxOffers, uint256 maxRaising, uint256 launchTime, uint256 offers, uint256 funds, uint256 lastPrice, uint256 K, uint256 T, uint256 status) ti, uint256 funds) pure returns (uint256)",
  "function calcBuyCost(tuple(address base, address quote, uint256 template, uint256 totalSupply, uint256 maxOffers, uint256 maxRaising, uint256 launchTime, uint256 offers, uint256 funds, uint256 lastPrice, uint256 K, uint256 T, uint256 status) ti, uint256 amount) pure returns (uint256)",
  "function calcLastPrice(tuple(address base, address quote, uint256 template, uint256 totalSupply, uint256 maxOffers, uint256 maxRaising, uint256 launchTime, uint256 offers, uint256 funds, uint256 lastPrice, uint256 K, uint256 T, uint256 status) ti) pure returns (uint256)",
  "function calcSellCost(tuple(address base, address quote, uint256 template, uint256 totalSupply, uint256 maxOffers, uint256 maxRaising, uint256 launchTime, uint256 offers, uint256 funds, uint256 lastPrice, uint256 K, uint256 T, uint256 status) ti, uint256 amount) pure returns (uint256)",
  "function calcTradingFee(tuple(address base, address quote, uint256 template, uint256 totalSupply, uint256 maxOffers, uint256 maxRaising, uint256 launchTime, uint256 offers, uint256 funds, uint256 lastPrice, uint256 K, uint256 T, uint256 status) ti, uint256 funds) view returns (uint256)",
  "function CLICK_FUN() view returns (address)",
  "function DEFAULT_ADMIN_ROLE() view returns (bytes32)",
  "function encodeCreateTokenArg() pure returns (bytes)",
  "function getRoleAdmin(bytes32 role) view returns (bytes32)",
  "function hasRole(bytes32 role, address account) view returns (bool)",
  "function nameOfRole(bytes32 role) pure returns (string)",
  "function owner() view returns (address)",
  "function PANCAKE_FACTORY() view returns (address)",
  "function PANCAKE_ROUTER() view returns (address)",
  "function proxiableUUID() view returns (bytes32)",
  "function ROLE_DEPLOYER() view returns (bytes32)",
  "function ROLE_OPERATOR() view returns (bytes32)",
  "function signer() view returns (address)",
  "function STATUS_ADDING_LIQUIDITY() view returns (uint256)",
  "function STATUS_COMPLETED() view returns (uint256)",
  "function STATUS_HALT() view returns (uint256)",
  "function STATUS_TRADING() view returns (uint256)",
  "function supportsInterface(bytes4 interfaceId) view returns (bool)",
  "function WBNB() view returns (address)",

  // Events
  "event AdminChanged(address previousAdmin, address newAdmin)",
  "event BeaconUpgraded(address indexed beacon)",
  "event Initialized(uint8 version)",
  "event LiquidityAdded(address base, uint256 offers, address quote, uint256 funds)",
  "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
  "event RoleAdminChanged(bytes32 indexed role, bytes32 indexed previousAdminRole, bytes32 indexed newAdminRole)",
  "event RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)",
  "event RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)",
  "event TokenCreate(address creator, address token, uint256 requestId, string name, string symbol, uint256 totalSupply, uint256 launchTime, uint256 launchFee)",
  "event TokenPurchase(address token, address account, uint256 price, uint256 amount, uint256 cost, uint256 fee, uint256 offers, uint256 funds)",
  "event TokenSale(address token, address account, uint256 price, uint256 amount, uint256 cost, uint256 fee, uint256 offers, uint256 funds)",
  "event TradeStop(address token)",
  "event Upgraded(address indexed implementation)"
] as const;
